### ISSUE TITLE
Config to disable printing cache date comment

### ISSUE THREAD

**Issue by dmyers** [Anahkiasen/flatten#19]
What do you think about adding an option to disable the printing of the cache date comment that is appended to the page html?

**Comment by moorer2k** [comment]
Personally I like the commenting system! I just changed some of the code to store it in a javascript variable in which I assign a timestamp for that cached page so that users can manually refresh, if they wish to update the page! For example: http://loldir.com/vacation/na . 

It would actually be nice to be able to manipulate this field more easier! Great package, keep it up!

**Comment by Anahkiasen** [comment]
Done on develop, can use it through the `1.1.*@dev` branch alias. See the `timestamp` option.

**Comment by dmyers** [comment]
Thanks!

**Comment by moorer2k** [comment]
Awesome, thank you for this!
